@echo off
copy d:\tabl0.asl s:\DAYS.PRO\ZXS\tabl0.asl
copy d:\tabl_ed.asl s:\DAYS.PRO\ZXS\tabl_ed.asl
copy d:\tabl_dd.asl s:\DAYS.PRO\ZXS\tabl_dd.asl
copy d:\tabl_fd.asl s:\DAYS.PRO\ZXS\tabl_fd.asl
copy d:\tabl_cb.asl s:\DAYS.PRO\ZXS\tabl_cb.asl
copy d:\tabl_ddc.asl s:\DAYS.PRO\ZXS\tabl_ddc.asl
copy d:\tabl_fdc.asl s:\DAYS.PRO\ZXS\tabl_fdc.asl
copy d:\zxs.asl s:\DAYS.PRO\ZXS\zxs.asl
copy d:\zxs_ofs.asi s:\DAYS.PRO\ZXS\zxs_ofs.asi
copy d:\zxs_adrs.asi s:\DAYS.PRO\ZXS\zxs_adrs.asi
copy d:\zxs_keys.asi s:\DAYS.PRO\ZXS\zxs_keys.asi
copy d:\zxs_con.asi s:\DAYS.PRO\ZXS\zxs_con.asi
copy d:\globals.asi s:\DAYS.PRO\ZXS\globals.asi
echo Всё скопировано на винчестер.
                  