@echo off
copy s:\DAYS.PRO\ZXS\tabl0.asl d:\tabl0.asl
copy s:\DAYS.PRO\ZXS\tabl_ed.asl d:\tabl_ed.asl
copy s:\DAYS.PRO\ZXS\tabl_dd.asl d:\tabl_dd.asl
copy s:\DAYS.PRO\ZXS\tabl_fd.asl d:\tabl_fd.asl
copy s:\DAYS.PRO\ZXS\tabl_cb.asl d:\tabl_cb.asl
copy s:\DAYS.PRO\ZXS\tabl_ddc.asl d:\tabl_ddc.asl
copy s:\DAYS.PRO\ZXS\tabl_fdc.asl d:\tabl_fdc.asl
copy s:\DAYS.PRO\ZXS\zxs.asl d:\zxs.asl
copy s:\DAYS.PRO\ZXS\zxs_ofs.asi d:\zxs_ofs.asi
copy s:\DAYS.PRO\ZXS\zxs_adrs.asi d:\zxs_adrs.asi
copy s:\DAYS.PRO\ZXS\zxs_keys.asi d:\zxs_keys.asi
copy s:\DAYS.PRO\ZXS\zxs_con.asi d:\zxs_con.asi
copy s:\DAYS.PRO\ZXS\globals.asi d:\globals.asi
copy s:\DAYS.PRO\ZXS\zxs.bat d:\zxs.bat
copy s:\DAYS.PRO\ZXS\zxs_link.bat d:\zxs_link.bat
copy s:\DAYS.PRO\ZXS\zxs.dat d:\zxs.dat
copy s:\DAYS.PRO\ZXS\zxs.tap d:\zxs.tap
echo Всё скопировано на диск-ОЗУ.
